
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['daily_summary_gui.py'],
    pathex=[],
    binaries=[],
    datas=[('quarterly sheets', 'quarterly sheets')] if os.path.exists('quarterly sheets') else [],
    hiddenimports=[
        'daily_summary_generator',
        'pandas',
        'pandas.core.common',
        'pandas.core.ops',
        'pandas.tseries.offsets',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.timezones',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.styles.colors',
        'openpyxl.styles.fills',
        'openpyxl.styles.fonts',
        'openpyxl.styles.borders',
        'openpyxl.styles.alignment',
        'openpyxl.utils',
        'openpyxl.utils.cell',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'docx',
        'docx.shared',
        'docx.enum',
        'docx.enum.table',
        'docx.oxml',
        'docx.oxml.ns',
        'docx.oxml.shared',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'threading',
        'datetime',
        'argparse',
        'io',
        'contextlib',
        'subprocess'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='DailySummaryGenerator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico' if os.path.exists('icon.ico') else None,
)
